namespace TCLDecompiler {
	public enum Opcode {
		Done = 0,
		Push1, Push4, Pop, Dup, StrConcat1,
		InvokeStk1, InvokeStk4, EvalStk, ExprStk,
		LoadScalar1, LoadScalar4, LoadScalarStk,
		LoadArray1, LoadArray4, LoadArrayStk, LoadStk,
		StoreScalar1, StoreScalar4, StoreScalarStk,
		StoreArray1, StoreArray4, StoreArrayStk, StoreStk,
		IncrScalar1, IncrScalarStk, IncrArray1, IncrArrayStk, IncrStk,
		IncrScalar1Imm, IncrScalarStkImm, IncrArray1Imm, IncrArrayStkImm, IncrStkImm,
		Jump1, Jump4, JumpTrue1, JumpTrue4, JumpFalse1, JumpFalse4,
		Lor, Land, Bitor, Bitxor, Bitand, Eq, Neq, Lt, Gt, Le, Ge, Lshift, Rshift,
		Add, Sub, Mult, Div, Mod, Uplus, Uminus, Bitnot, Not,
		CallBuiltinFunc1, CallFunc1,
		TryCvtToNumeric,
		Break, Continue,
		ForeachStart4, ForeachStep4,
		BeginCatch4, EndCatch,
		PushResult, PushReturnCode,
		StrEq, StrNeq, StrCmp, StrLen, StrIndex, StrMatch,
		List, ListIndex, ListLength,
		AppendScalar1, AppendScalar4, AppendArray1, AppendArray4, AppendArrayStk, AppendStk,
		LappendScalar1, LappendScalar4, LappendArray1, LappendArray4, LappendArrayStk, LappendStk,
		ListIndexMulti, Over, LsetList, LsetFlat,
		ReturnImm, Expon, ExpandStart, ExpandStktop, InvokeExpanded, ListIndexImm, ListRangeImm, StartCmd,
		ListIn, ListNotIn, PushReturnOptions, ReturnStk,
		DictGet, DictSet, DictUnset, DictIncrImm, DictAppend,
		DictLappend, DictFirst, DictNext, DictDone, DictUpdateStart, DictUpdateEnd,
		JumpTable, Upvar, Nsupvar, Variable, Syntax, Reverse, Regexp,
		ExistScalar, ExistArray, ExistArrayStk, ExistStk,
		Nop, ReturnCodeBranch,
		UnsetScalar, UnsetArray, UnsetArrayStk, UnsetStk,
		DictExpand, DictRecombineStk, DictRecombineImm, DictExists, DictVerify,
		StrMap, StrFind, StrFindLast, StrRangeImm, StrRange,
		Yield, CoroutineName, Tailcall, NsCurrent,
		InfoLevelNum, InfoLevelArgs, ResolveCommand,
		TclooSelf, TclooClass, TclooNs, TclooIsObject,
		ArrayExistsStk, ArrayExistsImm, ArrayMakeStk, ArrayMakeImm,
		InvokeReplace, ListConcat, ExpandDrop,
		ForeachStart, ForeachStep, ForeachEnd, LmapCollect,
		StrTrim, StrTrimLeft, StrTrimRight, ConcatStk, StrUpper, StrLower, StrTitle, StrReplace,
		OriginCommand, TclooNext, TclooNextClass, YieldToInvoke, NumType, TryCvtToBoolean, StrClass,
		LappendList, LappendListArray, LappendListArrayStk, LappendListStk,
		ClockRead
	}
}
